services:
  db:
    image: mysql:8.0
    container_name: gametracker-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: gametracker
      MYSQL_USER: gameuser
      MYSQL_PASSWORD: gamepassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  app:
    build: .
    container_name: gametracker-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: gameuser
      DB_PASSWORD: gamepassword
      DB_NAME: gametracker
    volumes:
      - ./data:/app/data
      - ./src:/app/src
      - ./scripts:/app/scripts
      - ./output:/app/output
    # lignes ici rajoutées pour garder le conteneur en vie pour que cela focntionne avec exec comme prévu dans le README
    stdin_open: true
    tty: true
    command: tail -f /dev/null

volumes:
  db_data:
